<a href="https://colab.research.google.com/github/Bighnaraj19/DMDW/blob/main/dmdw4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.zeros((3,3))
print(a)
print(a.shape)
b=np.ones((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a = np.random.random((3,3))
print(a)

[[0.37510916 0.34094554 0.59396996]
 [0.8381419  0.66996862 0.2032233 ]
 [0.96311011 0.12576307 0.37896031]]


In [ ]:
a = np.arange(20)
print(a)
print(a[1:7:2])
print(a[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 3 5]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [ ]:
a = np.array([[12,11],[3,7],[5,13]])
b = np.random.random((3,2))
print(a.shape)
print(a+b)
print(a-b)
print(a*b)
print(a>10)


(3, 2)
[[12.23452012 11.97955193]
 [ 3.62988538  7.83976541]
 [ 5.75457665 13.83850797]]
[[11.76547988 10.02044807]
 [ 2.37011462  6.16023459]
 [ 4.24542335 12.16149203]]
[[ 2.8142414  10.77507122]
 [ 1.88965614  5.87835788]
 [ 3.77288326 10.90060361]]
[[ True  True]
 [False False]
 [False  True]]


In [ ]:
a = np.array([[12,11],[3,7],[5,13]])
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))
print(a.T)

[20 31]
[23 10 18]
[[12  3  5]
 [11  7 13]]


In [ ]:
a = np.array([[22,11,15],[5,7,3]])
print(a)
w=np.array([1.0,1.1,1.2])
print(w)
print(a+w)


[[22 11 15]
 [ 5  7  3]]
[1.  1.1 1.2]
[[23.  12.1 16.2]
 [ 6.   8.1  4.2]]
